/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jintipu_controller_VeriCodeProc */

#ifndef _Included_com_example_util_VeriCodeProc
#define _Included_com_example_util_VeriCodeProc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jintipu_controller_VeriCodeProc
 * Method:    veriCode
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_util_VeriCodeProc_veriCode
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
